### ISSUE TITLE
repo missing license

### ISSUE THREAD

**Issue by max-mapper** [superherojs/superherojs#34]
hey, can you add a license.md file to the repo? i'd like to know if i'm allowed to use some CSS from here

cheers,

max

**Comment by kimjoar** [comment]
@maxogden Agreed, we should add a license.

@olav As the creator of the CSS magic, what do you think?

**Comment by olav** [comment]
@kjbekkelund Agreed, but I don't think the content and the design can use the same license. 

The content (i.e. the list of resources) could be licensed under a Creative Commons license (or something). 

The design is trickier. Others can't use the background images (standard stock photo license), and you can't really use the CSS without the images. So, because of the images, standard copyright should apply to the design elements (which it does by default -- the content license should strictly specify that it only applies to the textual content).

**Comment by kimjoar** [comment]
@olav Agreed. What about http://creativecommons.org/licenses/by/3.0/ for the content, MIT for "the code", except for the images where standard copyright applies?

**Comment by olav** [comment]
@kjbekkelund Sounds good. A LICENSE.md with something like:

```
Content: CC BY 3.0 <link> 
Code: MIT <link>
Images: Copyright SuperheroJS 2k13
```

**Comment by kimjoar** [comment]
@olav Looks good to me. U fix? :)

**Comment by olav** [comment]
@kjbekkelund I fix! Something like this?

https://github.com/superherojs/superherojs/blob/gh-pages/LICENSE.md

**Comment by kimjoar** [comment]
@olav Looks good to me.

@maxogden Does that solve the issue? :)

**Comment by max-mapper** [comment]
yep, thanks!
